MIGRATE_PATH=setup/db/migrations
DATABASE_URL=postgres://user_name:password@host_name:port/db_name?sslmode=disable

migrate-up:
	migrate -path $(MIGRATE_PATH) -database "$(DATABASE_URL)" up

migrate-down:
	migrate -path $(MIGRATE_PATH) -database "$(DATABASE_URL)" down 1

migrate-force:
	migrate -path $(MIGRATE_PATH) -database "$(DATABASE_URL)" force $(v)
